config/routes.rb
DcTestApp::Application.routes.draw do

  root 'colors#index'
  resources :colors

end

app/models/color.rb
class Color < ActiveRecord::Base
end

app/models/name.rb
class Name < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
	def index
		@color = Color.order("RANDOM()").first
	end 

	def new
		@color = Color.new
	end

	def create
		Color.create(color_params)
		redirect_to root_path
	end

	private
	
	def color_params
		params.require(:color).permit(:hex, :name)
	end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/colors/index.html.erb
<div class="col-xs-4 col-xs-offset-4 boxy">
	<h1 style="color: #<%= @color.hex %>"><%= @color.name.inspect %></h2>
	<h2>is the new Black</h2>

<%= link_to 'Add New Color', new_color_path, :class => "btn-success btn" %>
</div>

app/views/colors/new.html.erb
<div class="boxy">
	<h1>Black is boring. Suggest a color?</h1>
	<%= simple_form_for @color do |f| %>
	<%= f.input :hex, :label => "Hex #: " %>
	<%= f.input :name, :label => "Color Name: " %>
	<%= f.submit 'Create', :class => "btn-primary" %>
	<% end %>
</div>

app/views/files/index.html.erb
<h1><%= @color.inspect %></h1>

<h1>Enter a color</h1>
<%= simple_form_for @color do |f| %>
	<%= f.input :hex %>
	<%= f.input :name %>
	<%= f.submit 'Create' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DcTestApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>